# Generated by Django 5.0.6 on 2024-05-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateID', models.CharField(max_length=20)),
                ('ownerName', models.CharField(max_length=100)),
                ('vehicleModel', models.CharField(max_length=50)),
            ],
        ),
    ]
